"""Build the dashboard data from the original art (images/P.DIALS.bin, BBC mode 5).

  python dash.py [preview.png]        (run from the CoCo directory)

The original dashboard is 128 x 56 pixels of 4 colours; each pixel is two screen pixels
wide, so on the 256 x 192 1bpp CoCo screen a pixel is two bits (nonzero colour = lit) and
the 56 lines become 42 rows (the uniform 3/4 vertical scale): of every 4 source lines
0 -> row 0, 1|2 -> row 1, 3 -> row 2.

  gen/dashfull.bin   the whole 42 x 32 byte image (blitted to both pages at start-up)
  gen/dashscan.bin   its columns 6..25 (the scanner, its frame and the compass) for the
                     per-frame restore, each row as three chunks in reverse order
                     (see SCANRESTORE in flight/dash.asm)
  gen/dash.inc       the small tables of the dial code
"""
import sys
from pathlib import Path
from dashimg import pixels, W

ROOT = Path(__file__).resolve().parents[2]
ROWS = 42
SC0, SCN = 6, 20            # scanner restore: first byte column, byte columns
# the original's colours 1 red, 2 yellow, 3 green as the CoCo's artifact pairs: red '10', yellow as white
# '11', green as blue '01'
RED = 2
SHIP = 3                    # the ships on the scanner: white, so they show against the red grid
PAIR = {1: RED, 2: 3, 3: 3 - RED}                     # the two bits of artifact red ('10'; '01' is blue): also the scanner's ship dots


def runs(px, x0, x1, y0, y1, col):
    """vertical runs of source lines holding pixels of colour col in columns x0..x1"""
    out, cur = [], None
    for y in range(y0, y1):
        on = any(px[y][x] == col for x in range(x0, x1 + 1))
        if on and cur is None:
            cur = y
        if not on and cur is not None:
            out.append((cur, y))
            cur = None
    return out


def image():
    """The art as 42 rows of 128 lit/unlit pixels. The graphics are scaled 4 lines -> 3
    rows; the text is not: the original's labels are only 5 lines tall, so a scaled copy
    loses their strokes. Each label is copied line for line instead (5 rows) and placed
    in its slot: the label i of a column at row 6i + 1 (the last one, and ELITE, one
    row higher to keep clear of the frame)."""
    px = pixels()
    ob = []
    for r in range(ROWS):
        g, k = divmod(r, 3)
        src = {0: [4 * g], 1: [4 * g + 1, 4 * g + 2], 2: [4 * g + 3]}[k]
        ob.append([next((px[s][x] for s in src if px[s][x]), 0) for x in range(W)])

    def labels(x0, x1, y0, y1, col, clear_rows, tops):
        for r in clear_rows:
            for x in range(x0, x1 + 1):
                ob[r][x] = 0
        rs = runs(px, x0, x1, y0, y1, col)
        for i, (a, b) in enumerate(rs):
            top = tops(i, len(rs))
            ys = [y for y in range(a, b)]
            if len(ys) > 5:
                del ys[1]               # a 6 line glyph: its first stem line goes
            for j, y in enumerate(ys):
                for x in range(x0, x1 + 1):
                    if px[y][x] == col:
                        ob[top + j][x] = col
        return rs
    # the six labels at the left, the seven at the right (the digit 4 is 6 lines: its
    # stem loses a line), ELITE
    labels(1, 7, 1, 48, 1, range(0, 36), lambda i, n: 6 * i + 1)
    rs = labels(121, 126, 1, 55, 1, range(0, 41), lambda i, n: 6 * i + 1 if i < 6 else 36)
    assert len(rs) == 7, rs
    for x in range(50, 77):
        for r in range(36, 41):
            ob[r][x] = 0
    for y in range(49, 54):
        for x in range(50, 77):
            if px[y][x] == 3:
                ob[36 + y - 49][x] = 3
    rows = []
    for r in range(ROWS):
        line = bytearray(32)
        for x in range(W):
            if ob[r][x]:
                line[x // 4] |= PAIR[ob[r][x]] << (6 - 2 * (x % 4))
        rows.append(bytes(line))
    return rows


def main():
    rows = image()
    (ROOT / 'coco-source' / 'gen' / 'dashfull.bin').write_bytes(b''.join(rows))
    scan = bytearray()
    for r in rows:
        c = r[SC0:SC0 + SCN]
        scan += c[13:20] + c[6:13] + c[0:6]
    (ROOT / 'coco-source' / 'gen' / 'dashscan.bin').write_bytes(bytes(scan))

    out = ['; Generated by tools/dash.py: tables of the dashboard code']

    def table(name, entries, per=8):
        out.append(name)
        for i in range(0, len(entries), per):
            out.append('        FCB ' + ','.join('$%02X' % v for v in entries[i:i + per]))
    # a bar of q (0..16) pixels, 2 bits each, as 4 bytes (left aligned)
    bar = []
    for q in range(17):
        for b in range(4):
            n = max(0, min(4, q - 4 * b))
            bar.append((0xFF00 >> (2 * n)) & 0xFF)
    table('BARTAB', bar, 4)
    # a one pixel marker at position m (0..15), as 4 bytes
    mk = []
    for m in range(16):
        for b in range(4):
            mk.append(0xC0 >> (2 * (m % 4)) if m // 4 == b else 0)
    table('MARKTAB', mk, 4)
    # the ships on the scanner in the scanner's colour: a 2 x 2 pixel dot at pixel (p & 3), as 2
    # bytes, and a one pixel wide stick
    dots = []
    for p in range(4):
        v = (SHIP << (6 - 2 * p)) | (SHIP << (4 - 2 * p)) if p < 3 else (SHIP << 0)
        d = (v << 8) if p < 3 else ((SHIP << 0) << 8) | (SHIP << 6)
        dots.append('$%04X' % d)
    out.append('DOTMASK FDB ' + ','.join(dots))
    out.append('STKMASK FCB ' + ','.join('$%02X' % (SHIP << (6 - 2 * p)) for p in range(4)))
    (ROOT / 'coco-source' / 'gen' / 'dash.inc').write_text('\n'.join(out) + '\n')

    if len(sys.argv) > 1:
        from PIL import Image
        im = Image.new('L', (256, ROWS))
        for y, r in enumerate(rows):
            for x in range(256):
                if r[x // 8] & (0x80 >> (x % 8)):
                    im.putpixel((x, y), 255)
        im.resize((1024, ROWS * 4), Image.NEAREST).save(sys.argv[1])
    print('dash: %d rows, scanner image %d bytes' % (ROWS, len(scan)))


main()
