"""Where did the files go? Reads a DECB disk image and writes gen/disksec.inc with the
granule chains of two files (DECB hands out granules wherever it likes: here 34, 35, 32, 33):
ELITE.DAT, the overlay blob, and ELITE.SAV, the room for saved commanders (2 granules, 18
sectors).

  python diskinfo.py build/elite.dsk ELITE DAT ELITE SAV
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
img = Path(sys.argv[1]).read_bytes()


def sector(track, sec):
    o = (track * 18 + sec - 1) * 256
    return img[o:o + 256]


fat = sector(17, 2)


def chain_of(name, ext):
    name = name.ljust(8).encode()
    ext = ext.ljust(3).encode()
    first = None
    for s in range(3, 12):
        d = sector(17, s)
        for i in range(0, 256, 32):
            e = d[i:i + 32]
            if e[0] not in (0, 0xFF) and e[:8] == name and e[8:11] == ext:
                first = e[13]
    if first is None:
        sys.exit('file not found: %s.%s' % (name.decode().strip(), ext.decode().strip()))
    chain = [first]
    while fat[chain[-1]] < 0xC0:
        chain.append(fat[chain[-1]])
    return chain


dat = chain_of(sys.argv[2], sys.argv[3])
sav = chain_of(sys.argv[4], sys.argv[5]) if len(sys.argv) > 5 else [0]
(ROOT / 'coco-source' / 'gen' / 'disksec.inc').write_text(
    '; Generated by tools/diskinfo.py: the granules of ELITE.DAT in file order, and of ELITE.SAV\n'
    'DISKGRAN FCB %s\nSAVEGRAN FCB %s\n' % (
        ','.join(map(str, (dat + [0] * 64)[:64])),      # fixed size: the program's layout must not depend on it
        ','.join(map(str, (sav + [0] * 4)[:4]))))
print('file granules', dat, 'save granules', sav)
