"""Polygon loops for the shaded mode (the Easter egg): for every face of every blueprint, the
outline of the face as an ordered loop of vertex numbers, found from the blueprint's edges.

An edge records the two faces it belongs to, so the edges of a face form (at least) one closed
loop through its vertices. Faces also have inner edges (details) hanging off the outline or
crossing it; the loop of largest area (in the face's own plane) is taken as the polygon, the
other edges stay lines. Faces without a loop of 3 or more vertices get an empty list.

  python faceloops.py <original main-sources dir> <out.inc> [-v]

Output (one table per blueprint, in the order of tools/ships.py's SHIPLIST):

  LOOPS_<name>   FCB count, vertex*4 ...   one entry per face, in face order, ended by the next
                                           face's entry; FACEOFS gives where each starts

For the runtime: LOOPTAB_<name> is FDB per face -> its loop (so a face's loop is two table
lookups away); the loops are in the SHIPS segment next to their blueprints.
"""
import math
import sys
from pathlib import Path

import ships


def face_loops(verts, edges, faces):
    nfaces = len(faces)
    out = []
    for f in range(nfaces):
        adj = {}
        for kind, (v1, v2, f1, f2, vis) in edges:
            if f1 == f or f2 == f:
                adj.setdefault(v1, []).append(v2)
                adj.setdefault(v2, []).append(v1)
        # all simple cycles through the graph by DFS from every vertex (graphs are tiny)
        best, best_area = None, 0.0
        nx, ny, nz = faces[f][1][:3]
        nlen = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
        seen = set()

        def area(loop):
            # twice the area vector projected on the face normal (shoelace in 3D)
            sx = sy = sz = 0.0
            for i in range(len(loop)):
                ax, ay, az = verts[loop[i]][1][:3]
                bx, by, bz = verts[loop[(i + 1) % len(loop)]][1][:3]
                sx += ay * bz - az * by
                sy += az * bx - ax * bz
                sz += ax * by - ay * bx
            return abs(sx * nx + sy * ny + sz * nz) / nlen

        def dfs(start, v, path, visited):
            nonlocal best, best_area
            for w in adj.get(v, []):
                if w == start and len(path) >= 3:
                    key = frozenset(path)
                    a = area(path)
                    if a > best_area + 1e-9:
                        best, best_area = list(path), a
                elif w not in visited and w > start:        # each cycle once, from its smallest vertex
                    visited.add(w)
                    path.append(w)
                    dfs(start, w, path, visited)
                    path.pop()
                    visited.discard(w)

        for s in sorted(adj):
            dfs(s, s, [s], {s})
        out.append(best)
    return out


def main(src, outp, verbose=False):
    srcdir = Path(src)
    blueprints = {}
    for fn in ships.SRC_ORDER:
        p = srcdir / fn
        if p.exists():
            for k, v in ships.parse_blueprints(p.read_text(encoding='latin-1')).items():
                blueprints.setdefault(k, v)
    lines = ['; Generated by tools/faceloops.py: the outline of every face of every blueprint',
             '; as a loop of vertex numbers * 4 (the offsets of TRANSFORM\'s projected vertices).']
    stats = []
    for name, (hdr, verts, edges, faces) in blueprints.items():
        loops = face_loops(verts, edges, faces)
        lines.append('LOOPS_' + name)
        starts = []
        n = 0
        for lp in loops:
            starts.append(n)
            if lp:
                lines.append('        FCB %d,%s' % (len(lp), ','.join(str(v * 4) for v in lp)))
                n += 1 + len(lp)
            else:
                lines.append('        FCB 0')
                n += 1
        lines.append('LOOPTAB_' + name)
        for st in starts:
            lines.append('        FDB LOOPS_%s+%d' % (name, st))
        none = sum(1 for lp in loops if not lp)
        stats.append((name, len(faces), none, sum(len(lp) + 1 for lp in loops if lp) + 2 * len(faces)))
    Path(outp).write_text('\n'.join(lines) + '\n')
    if verbose:
        tot = 0
        for name, nf, none, size in stats:
            tot += size
            print('%-28s faces %2d without loop %d bytes %d' % (name, nf, none, size))
        print('total', tot)


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], '-v' in sys.argv)
