"""Generates gen/linefast.inc: the unrolled interior loops of LINE.

A shallow line is drawn from both ends towards the middle, each half with the same
kind of loop (8 pixels per pass, the pixel masks are immediates, the row byte is
accumulated in A and written out only when the line steps to the next row or the byte
ends). Entering a loop in the middle starts the line at any bit of its first byte; both
halves end on a byte boundary, so no partial last byte is needed.

  fd / fu : left half, left to right,  stepping +32 / -32 rows  (line going down / up)
  rd / ru : right half, right to left, stepping -32 / +32 rows  (line going down / up)

B = error, X = screen byte, A = row byte accumulator, <fcnt = passes left.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / 'gen'


def chain(pfx, ltr, step, final):
    out = []
    order = range(8) if ltr else range(7, -1, -1)
    xs = '1' if ltr else '-1'
    out.append('%s_top CLRA' % pfx)
    for n, p in enumerate(order):
        mask = 0x80 >> p
        nxt = '%s_b%d' % (pfx, list(order)[n + 1]) if n < 7 else '%s_end' % pfx
        out.append('%s_b%d ORA #$%02X' % (pfx, p, mask))
        out.append('        SUBB <ldy8')
        out.append('        BCC %s' % nxt)
        out.append('        ADDB <ldx8')
        out.append('        STA <tmp')
        out.append('        LDA ,X')
        out.append('        EORA <tmp')
        out.append('        STA ,X')
        out.append('        LEAX %s,X' % step)
        out.append('        CLRA')
    out.append('%s_end STA <tmp' % pfx)
    out.append('        LDA ,X')
    out.append('        EORA <tmp')
    out.append('        STA ,X')
    out.append('        LEAX %s,X' % xs)
    out.append('        DEC <fcnt')
    out.append('        LBNE %s_top' % pfx)
    out.append('        %s' % final)
    return out


lines = ['; Generated by tools/linegen.py: the unrolled loops of LINE (two-ended).']
lines += chain('fd', True, '32', 'LBRA ln_right')
lines += chain('fu', True, '-32', 'LBRA ln_right')
lines += chain('rd', False, '-32', 'RTS')
lines += chain('ru', False, '32', 'RTS')
for pfx in ('fd', 'fu', 'rd', 'ru'):
    lines.append('%sENT   FDB %s' % (pfx.upper(), ','.join('%s_b%d' % (pfx, p) for p in range(8))))
(ROOT / 'linefast.inc').write_text('\n'.join(lines) + '\n')
