"""The resident program's labels as EQUs for the overlay segments: gen/mainsyms.inc.

  python mainsyms.py        (run from the CoCo directory; reads build/elite.map)

Labels in the low/main resident ranges and the persistent PERF segment are exported; the constants of
engine/vars.inc and engine/types.inc are included by the segments themselves.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
out = ['; Generated by tools/mainsyms.py: the resident program\'s labels']
seen = set()
constants = set()
for header in ('vars.inc', 'types.inc'):
    for line in (ROOT / 'coco-source' / 'engine' / header).read_text().splitlines():
        match = re.match(r'(\S+)\s+EQU\b', line)
        if match:
            constants.add(match.group(1))
mp = ROOT / 'build' / 'elite.map'
if mp.exists():
    for line in open(mp):
        m = re.match(r'Symbol: (\S+) \(.*\) = ([0-9A-Fa-f]+)', line)
        if m and not m.group(1).startswith('@') and m.group(1) not in constants:
            v = int(m.group(2), 16)
            if (0x0E00 <= v < 0x7F00 or 0xEE00 <= v < 0xF000 or 0xB600 <= v < 0xB800) and m.group(1) not in seen:
                seen.add(m.group(1))
                out.append('%-24s EQU $%04X' % (m.group(1), v))
(ROOT / 'coco-source' / 'gen' / 'mainsyms.inc').write_text('\n'.join(out) + '\n')
print('mainsyms: %d labels' % len(seen))
