"""Build the cartridge image build/elite.rom (Super Program Pak style banked ROM).

  python mkcart.py <lwasm>

The ROM is 16K pages seen at $C000-$FEFF (write the page number to $FF40); the top 256
bytes of a page are hidden behind the I/O area, so an image "stream" of 256-byte sectors
puts 63 sectors in each page. Stream layout (sector numbers):

    0-3     boot code (boot/cartboot.asm) at $C000: copies the resident program to RAM
    4-90    the resident program (the LOADM segment at $2800, up to 87 sectors: STAGE is at $7F00)
    96-121  the title background (the segment at $0E00, up to 26 sectors: $0E00-$27FF)
    128-    the overlay blob (build/elite.dat), CARTSEC in gen/medium.inc
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
asm = sys.argv[1]
CORESEC, NCORE, BGSEC, NBG, BLOBSEC = 4, 87, 96, 26, 128
PAGE = 0x4000
PER_PAGE = 63

medium = (ROOT / 'coco-source' / 'gen' / 'medium.inc').read_text()
assert int(re.search(r'CARTSEC EQU (\d+)', medium).group(1)) == BLOBSEC

# the program as a DECB BIN: (load, data) segments, exec address
b = (ROOT / 'build' / 'elite.bin').read_bytes()
segs = {}
i = 0
while b[i] == 0:
    n = (b[i + 1] << 8) | b[i + 2]
    a = (b[i + 3] << 8) | b[i + 4]
    segs[a] = b[i + 5:i + 5 + n]
    i += 5 + n
assert b[i] == 0xFF
core, bg = segs[0x2800], segs[0x0E00]
assert len(core) <= NCORE * 256 and len(bg) <= NBG * 256, (len(core), len(bg))
ncore = (len(core) + 255) // 256
assert 0x2800 + ncore * 256 <= 0x7F00            # below the loader's STAGE buffer

(ROOT / 'coco-source' / 'gen' / 'bootlist.inc').write_text(
    '; Generated by tools/mkcart.py: destination, sectors, first sector of the image\n'
    'BOOTLIST\n        FDB $2800\n        FCB %d\n        FDB %d\n'
    '        FDB $0E00\n        FCB %d\n        FDB %d\n        FDB 0\n' % (ncore, CORESEC, NBG, BGSEC))
subprocess.run([asm, '-9', '--format=raw', '-I' + str(ROOT / 'coco-source'),
                '-o' + str(ROOT / 'build' / 'cartboot.bin'), '--map=' + str(ROOT / 'build' / 'cartboot.map'),
                str(ROOT / 'coco-source' / 'boot' / 'cartboot.asm')], check=True)
boot = (ROOT / 'build' / 'cartboot.bin').read_bytes()
assert len(boot) <= CORESEC * 256, len(boot)

blob = (ROOT / 'build' / 'elite.dat').read_bytes()
nsec = BLOBSEC + len(blob) // 256
stream = bytearray(nsec * 256)
stream[0:len(boot)] = boot
stream[CORESEC * 256:CORESEC * 256 + len(core)] = core
stream[BGSEC * 256:BGSEC * 256 + len(bg)] = bg
stream[BLOBSEC * 256:] = blob
npages = (nsec + PER_PAGE - 1) // PER_PAGE
npages = 1 << (npages - 1).bit_length()          # 1, 2, 4, 8 pages: 16K .. 128K
rom = bytearray(npages * PAGE)
for s in range(nsec):
    p, k = divmod(s, PER_PAGE)
    rom[p * PAGE + k * 256:p * PAGE + k * 256 + 256] = stream[s * 256:(s + 1) * 256]
(ROOT / 'build' / 'elite.rom').write_bytes(bytes(rom))
print('cartridge: %d pages (%dK), program %d sectors, boot %d bytes' % (npages, npages * 16, ncore, len(boot)))
