"""Overlay segments: pack the raw segment binaries into one blob, one sector (256 bytes)
granularity, and generate the include files the resident program uses.

  python segs.py        (run from the CoCo directory; reads build/<name>.bin/.map)

  build/elite.dat       the blob: every segment padded to whole sectors, back to back
  gen/segsyms.inc       EQUs for every symbol of every segment (addresses in RAM)
  gen/segtab.inc        SEGTAB: per segment  FDB load address, FCB sectors, FDB first sector
                        (first sector counted from the start of the blob)
  gen/medium.inc        where the blob starts on each medium (cartridge image, fixed)

The blob is placed at the start of its own file on the disk (ELITE.DAT, first file written,
see tools/diskinfo.py) and at a fixed sector of the cartridge image (tools/mkcart.py).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]        # CoCo/
SEGS = [('SHIPS', 0xC000, 0xF000),                # name, load address, end limit (the ship slots
        ('DASH', 0xF300, 0xFC00),                 # (the docked screens use the ships' place)
        ('DOCK', 0xC000, 0xF000)]                 # are at $F000, the explosion records at $FC00)
CART_BLOB_SECTOR = 128                            # blob at linear offset $8000 of the cartridge


def main():
    blob = bytearray()
    tab = []
    syms = []
    for name, addr, limit in SEGS:
        fn = ROOT / 'build' / (name.lower() + '.bin')
        data = fn.read_bytes() if fn.exists() else bytes(256)    # (a first pass without the segment)
        first = len(blob) // 256
        pad = (-len(data)) % 256
        blob += data + bytes(pad)
        nsec = len(blob) // 256 - first
        assert nsec < 256 and addr + nsec * 256 <= limit, (name, 'overlaps the variables at $%04X' % limit)
        tab.append((name, addr, nsec, first, len(data)))
        mapf = ROOT / 'build' / (name.lower() + '.map')
        for line in (open(mapf) if mapf.exists() and name != 'DOCK' else []):
            m = re.match(r'Symbol: (\S+) \(.*\) = ([0-9A-Fa-f]+)', line)
            if m and not m.group(1).startswith('@'):
                syms.append((m.group(1), int(m.group(2), 16)))
    (ROOT / 'build' / 'elite.dat').write_bytes(bytes(blob))
    g = ROOT / 'coco-source' / 'gen'
    out = ['; Generated by tools/segs.py: the symbols of the overlay segments.']
    for n, v in syms:
        out.append('%-24s EQU $%04X' % (n, v))
    (g / 'segsyms.inc').write_text('\n'.join(out) + '\n')
    out = ['; Generated by tools/segs.py: segment table (load address, sectors, first sector in the blob)',
           'NSEGS   EQU %d' % len(tab)]
    for i, (n, a, ns, f, ln) in enumerate(tab):
        out.append('SEG_%s EQU %d' % (n, i))
    out.append('SEGTAB')
    for n, a, ns, f, ln in tab:
        out.append('        FDB $%04X        ; %s: %d bytes' % (a, n, ln))
        out.append('        FCB %d' % ns)
        out.append('        FDB %d' % f)
    (g / 'segtab.inc').write_text('\n'.join(out) + '\n')
    (g / 'medium.inc').write_text('; Generated by tools/segs.py\nCARTSEC EQU %d       ; first sector of the blob in the cartridge image\n'
                                  % CART_BLOB_SECTOR)
    print('blob %d bytes, %d sectors' % (len(blob), len(blob) // 256),
          ', '.join('%s %d sec' % (n, ns) for n, a, ns, f, ln in tab))


main()
